/* ============================================================
   EL GRAND LEMONPRIX 🍋 — Bancos de datos del concurso
   Edita este archivo a tu gusto: añade o quita preguntas,
   productos y tópicos. Formato: ["pregunta", "respuesta"].
   ============================================================ */

/* ---------- RONDA 1 · EL ALUVIÓN (cultura general, respuesta corta) ---------- */
const BANCO_ALUVION = [
  ["¿Cuál es la capital de Francia?", "París"],
  ["¿Cuál es la capital de Italia?", "Roma"],
  ["¿Cuál es la capital de Portugal?", "Lisboa"],
  ["¿Cuál es la capital de Alemania?", "Berlín"],
  ["¿Cuál es la capital de Argentina?", "Buenos Aires"],
  ["¿Cuál es la capital de Egipto?", "El Cairo"],
  ["¿Cuál es la capital de Noruega?", "Oslo"],
  ["¿Cuál es la capital de Polonia?", "Varsovia"],
  ["¿Cuál es la capital de Australia?", "Canberra"],
  ["¿Cuál es la capital de Turquía?", "Ankara"],
  ["¿Cuál es la capital de Grecia?", "Atenas"],
  ["¿Qué río pasa por París?", "El Sena"],
  ["¿Qué río pasa por Londres?", "El Támesis"],
  ["¿En qué país está la Torre Eiffel?", "Francia"],
  ["¿En qué país está la Sagrada Familia?", "España"],
  ["¿En qué continente está el desierto del Sáhara?", "África"],
  ["¿Qué país europeo tiene forma de bota?", "Italia"],
  ["¿Cuál es la capital de Japón?", "Tokio"],
  ["¿Cuál es la capital de México?", "Ciudad de México"],
  ["¿Qué océano separa Europa de América?", "Atlántico"],
  ["¿Cuál es la isla más grande del mundo?", "Groenlandia"],
  ["¿En qué país está Machu Picchu?", "Perú"],
  ["¿Qué canal une el Atlántico con el Pacífico?", "Canal de Panamá"],
  ["¿Cuál es la capital de Rusia?", "Moscú"],
  ["¿Cuál es el país más grande del mundo?", "Rusia"],
  ["¿Cuál es la montaña más alta del mundo?", "Everest"],
  ["¿Qué planeta es conocido como el planeta rojo?", "Marte"],
  ["¿Qué gas expulsamos al respirar?", "Dióxido de carbono"],
  ["¿Cuál es el símbolo químico del oro?", "Au"],
  ["¿Cuál es la fórmula química del agua?", "H2O"],
  ["¿Cuál es el planeta más grande del sistema solar?", "Júpiter"],
  ["¿Cuál es el animal terrestre más rápido del mundo?", "Guepardo"],
  ["¿Qué órgano bombea la sangre?", "El corazón"],
  ["¿Cuál es el satélite natural de la Tierra?", "La Luna"],
  ["¿Cuál es la estrella más cercana a la Tierra?", "El Sol"],
  ["¿Cuál es el hueso más largo del cuerpo humano?", "El fémur"],
  ["¿Qué mide un termómetro?", "La temperatura"],
  ["¿Cuál es el animal más grande del mundo?", "La ballena azul"],
  ["¿Cómo se llama el proceso con el que las plantas fabrican su alimento?", "Fotosíntesis"],
  ["¿Qué metal es líquido a temperatura ambiente?", "El mercurio"],
  ["¿Cuál es la unidad de la corriente eléctrica?", "El amperio"],
  ["¿Cuántos planetas tiene el sistema solar?", "Ocho"],
  ["¿Qué planeta es famoso por sus anillos?", "Saturno"],
  ["¿Cómo se llama la transformación de oruga a mariposa?", "Metamorfosis"],
  ["¿Qué órganos usamos para respirar?", "Los pulmones"],
  ["¿En qué estado está el agua cuando es hielo?", "Sólido"],
  ["¿Qué fuerza nos mantiene pegados al suelo?", "La gravedad"],
  ["¿Qué ave pone los huevos más grandes?", "El avestruz"],
  ["¿Qué vitamina fabrica nuestro cuerpo con la luz del sol?", "La vitamina D"],
  ["¿En qué año llegó Colón a América?", "1492"],
  ["¿Qué muro cayó en 1989?", "El Muro de Berlín"],
  ["¿Qué civilización construyó las pirámides de Giza?", "La egipcia"],
  ["¿Quién fue el primer presidente de Estados Unidos?", "George Washington"],
  ["¿Qué guerra mundial comenzó en 1939?", "La Segunda Guerra Mundial"],
  ["¿Qué imperio tenía gladiadores?", "El Imperio romano"],
  ["¿Qué reina española financió el viaje de Colón?", "Isabel la Católica"],
  ["¿Qué barco «insumergible» se hundió en 1912?", "El Titanic"],
  ["¿Qué revolución comenzó en 1789?", "La Revolución Francesa"],
  ["¿Quién fue el primer hombre en pisar la Luna?", "Neil Armstrong"],
  ["¿En qué año pisó el hombre la Luna?", "1969"],
  ["¿Qué país regaló la Estatua de la Libertad a Estados Unidos?", "Francia"],
  ["¿Qué civilización construyó el Coliseo?", "La romana"],
  ["¿Qué pueblo construyó Chichén Itzá?", "Los mayas"],
  ["¿Qué emperador francés fue derrotado en Waterloo?", "Napoleón"],
  ["¿Cuál fue la capital del Imperio inca?", "Cuzco"],
  ["¿Qué rey inglés tuvo seis esposas?", "Enrique VIII"],
  ["¿Qué antigua ciudad fue enterrada por el volcán Vesubio?", "Pompeya"],
  ["¿Qué guerra duró cien años entre Inglaterra y Francia?", "La Guerra de los Cien Años"],
  ["¿Qué país dio primero el voto a las mujeres, en 1893?", "Nueva Zelanda"],
  ["¿Quién escribió el Quijote?", "Miguel de Cervantes"],
  ["¿Quién pintó la Mona Lisa?", "Leonardo da Vinci"],
  ["¿Quién pintó el techo de la Capilla Sixtina?", "Miguel Ángel"],
  ["¿Quién escribió Romeo y Julieta?", "Shakespeare"],
  ["¿Quién pintó los relojes blandos?", "Salvador Dalí"],
  ["¿Cuál es el museo más famoso de París?", "El Louvre"],
  ["¿Quién escribió La Odisea?", "Homero"],
  ["¿Qué pintor se cortó una oreja?", "Van Gogh"],
  ["¿Quién escribió El viejo y el mar?", "Hemingway"],
  ["¿Quién escribió La casa de Bernarda Alba?", "Federico García Lorca"],
  ["¿Quién pintó Las Meninas?", "Velázquez"],
  ["¿Qué arquitecto diseñó la Sagrada Familia?", "Antoni Gaudí"],
  ["¿Quién escribió El principito?", "Antoine de Saint-Exupéry"],
  ["¿Quién escribió Crimen y castigo?", "Dostoievski"],
  ["¿Quién pintó La joven de la perla?", "Vermeer"],
  ["¿Quién escribió Don Juan Tenorio?", "José Zorrilla"],
  ["¿Qué escultor creó El pensador?", "Rodin"],
  ["¿Quién escribió Alicia en el país de las maravillas?", "Lewis Carroll"],
  ["¿Quién pintó el Guernica?", "Pablo Picasso"],
  ["¿Quién escribió los libros de Harry Potter?", "J. K. Rowling"],
  ["¿Cuántos jugadores tiene un equipo de fútbol en el campo?", "Once"],
  ["¿En qué deporte se usa raqueta y volante?", "Bádminton"],
  ["¿Cada cuántos años se juega un Mundial de fútbol?", "Cada cuatro"],
  ["¿Qué tarjeta expulsa a un jugador de fútbol?", "La roja"],
  ["¿En qué deporte se hacen mates?", "Baloncesto"],
  ["¿Cuántos aros tiene el símbolo olímpico?", "Cinco"],
  ["¿Qué deporte practicaba Michael Jordan?", "Baloncesto"],
  ["¿De qué país es originario el taekwondo?", "Corea"],
  ["¿Cuánto dura un partido de fútbol reglamentario?", "90 minutos"],
  ["¿En qué deporte se compite en el Tour de Francia?", "Ciclismo"],
  ["¿Qué selección ganó el Mundial de fútbol de 2010?", "España"],
  ["¿En qué ciudad fueron los Juegos Olímpicos de 1992?", "Barcelona"],
  ["¿Cuántos puntos vale un triple en baloncesto?", "Tres"],
  ["¿En qué deporte se usa el término «birdie»?", "Golf"],
  ["¿Qué país es famoso por la lucha de sumo?", "Japón"],
  ["¿Qué tenista español es llamado el «Rey de la tierra batida»?", "Rafa Nadal"],
  ["¿Cuántos jugadores de voleibol hay en pista por equipo?", "Seis"],
  ["¿En qué deporte se juega un «Grand Slam»?", "Tenis"],
  ["¿Qué país ganó el Mundial de fútbol de 2014?", "Alemania"],
  ["¿Cuántos jugadores tiene un equipo de balonmano en pista?", "Siete"],
  ["¿Quién dirigió la película E.T.?", "Steven Spielberg"],
  ["¿Qué película tiene un parque lleno de dinosaurios?", "Parque Jurásico"],
  ["¿Qué grupo cantaba Hey Jude?", "The Beatles"],
  ["¿Qué actor interpreta a Iron Man?", "Robert Downey Jr."],
  ["¿Qué película de 1997 ganó 11 Óscar con un barco?", "Titanic"],
  ["¿Qué cantante era conocido como el «Rey del Pop»?", "Michael Jackson"],
  ["¿Qué película de Disney tiene a Simba de protagonista?", "El Rey León"],
  ["¿Qué actor interpreta a Jack Sparrow?", "Johnny Depp"],
  ["¿Cuántas teclas tiene un piano estándar?", "88"],
  ["¿Qué película trata de un ogro verde?", "Shrek"],
  ["¿Qué grupo español cantaba La Flaca?", "Jarabe de Palo"],
  ["¿En qué saga de películas aparece Darth Vader?", "Star Wars"],
  ["¿Qué instrumento tiene normalmente seis cuerdas?", "La guitarra"],
  ["¿Qué actriz protagoniza Los juegos del hambre?", "Jennifer Lawrence"],
  ["¿Qué película de Pixar trata sobre las emociones?", "Del Revés"],
  ["¿Qué cantante puertorriqueño canta Despacito?", "Luis Fonsi"],
  ["¿Qué superhéroe viene del planeta Krypton?", "Superman"],
  ["¿Qué banda lideraba Freddie Mercury?", "Queen"],
  ["¿Qué película de animación tiene a un robot llamado WALL-E?", "WALL-E"],
  ["¿Qué cantante es conocida como la «Reina del Pop»?", "Madonna"],
  ["¿Cuántas comunidades autónomas tiene España?", "17"],
  ["¿Cuál es la capital de Andalucía?", "Sevilla"],
  ["¿Cuál es el río más largo de España?", "El Tajo"],
  ["¿En qué isla española está el Teide?", "Tenerife"],
  ["¿Cuál es la capital de Cataluña?", "Barcelona"],
  ["¿Cuál es la moneda oficial de España?", "El euro"],
  ["¿Qué ciudad española tiene la Alhambra?", "Granada"],
  ["¿En qué ciudad se celebran los sanfermines?", "Pamplona"],
  ["¿Qué plato típico valenciano lleva arroz?", "La paella"],
  ["¿Qué baile es típico de Andalucía?", "El flamenco"],
  ["¿Cuántos colores tiene el arcoíris?", "Siete"],
  ["¿Cuántos días tiene un año bisiesto?", "366"],
  ["¿Cuántos lados tiene un hexágono?", "Seis"],
  ["¿Cuántas patas tiene una araña?", "Ocho"],
  ["¿Cuántas vidas se dice que tiene un gato?", "Siete"],
  ["¿Qué número representa la X romana?", "Diez"],
  ["¿Cuántas franjas tiene la bandera de España?", "Tres"],
  ["¿Cuántas letras tiene el abecedario español?", "27"],
  ["¿Cuál es el océano más grande del mundo?", "El Pacífico"],
  ["¿Cuál es la capital de Chile?", "Santiago"],
  ["¿Qué gas necesitamos para vivir?", "El oxígeno"],
  ["¿Cuál es el país con más población del mundo?", "India"]
];

/* ---------- RONDA 3 · EL PRECIO EXACTO ----------
   Puedes poner una imagen real añadiendo  img: "URL_de_la_imagen"  */
const BANCO_PRECIOS = [
  { nombre: "Un kilo de limones", emoji: "🍋", img: "", precio: 2.49 },
  { nombre: "Cafetera italiana (6 tazas)", emoji: "☕", img: "", precio: 19.95 },
  { nombre: "Auriculares inalámbricos", emoji: "🎧", img: "", precio: 34.99 },
  { nombre: "Mochila urbana", emoji: "🎒", img: "", precio: 27.50 },
  { nombre: "Vela aromática grande", emoji: "🕯️", img: "", precio: 8.99 },
  { nombre: "Tableta de chocolate premium", emoji: "🍫", img: "", precio: 3.75 },
  { nombre: "Botella térmica de 750 ml", emoji: "💧", img: "", precio: 16.90 },
  { nombre: "Pack de 5 pares de calcetines", emoji: "🧦", img: "", precio: 9.99 },
  { nombre: "Novela de bolsillo", emoji: "📚", img: "", precio: 11.95 },
  { nombre: "Planta de interior con maceta", emoji: "🪴", img: "", precio: 12.50 },
  { nombre: "Regleta de 6 enchufes", emoji: "🔌", img: "", precio: 14.95 },
  { nombre: "Botella de vino tinto crianza", emoji: "🍷", img: "", precio: 9.50 }
];

/* ---------- RONDA 4 · CONEXIÓN PERFECTA ----------
   {J} se sustituye por el nombre del jugador al que va dirigida */
const BANCO_CONEXION = [
  "¿Cuál es el plato favorito de {J}?",
  "¿Cuál es la canción favorita de {J}?",
  "¿A qué ciudad viajaría {J} mañana mismo?",
  "¿Cuál es el mayor miedo de {J}?",
  "¿Qué superpoder elegiría {J}?",
  "¿Cuál es la película favorita de {J}?",
  "¿Cuál es el postre favorito de {J}?",
  "¿Cuál fue la primera mascota de {J}?",
  "¿Cuál es el deporte favorito de {J}?",
  "¿Qué haría {J} con un millón de euros?",
  "¿Qué emoji usa más {J}?",
  "¿Cuál era la asignatura favorita de {J} en el colegio?",
  "¿Con qué personaje famoso cenaría {J}?",
  "¿Cuál es el mayor vicio de {J}?",
  "¿Cuál es la serie favorita de {J}?",
  "¿Qué regalo recuerda {J} con más cariño?",
  "¿Qué comida no probaría {J} nunca jamás?",
  "¿Qué apodo tenía {J} de pequeño/a?",
  "¿Qué aplicación usa más {J} en el móvil?",
  "¿Cuál es el plan perfecto de domingo para {J}?",
  "¿Cuál es el sabor de helado favorito de {J}?",
  "¿Qué es lo primero que compraría {J} si le tocara la lotería?",
  "¿En qué lugar del mundo sería más feliz {J}?",
  "¿Cuál es el talento oculto de {J}?"
];

/* ---------- RONDA 5 · EL DUELO FINAL (¡muy difíciles!, por temáticas) ---------- */
const BANCO_DUELO = {
  "📜 Historia": [
    ["¿En qué año cayó Constantinopla en manos de los otomanos?", "1453"],
    ["¿Qué tratado puso fin a la Guerra de los Treinta Años?", "La Paz de Westfalia"],
    ["¿Quién fue el primer emperador de Roma?", "Augusto (Octavio)"],
    ["¿En qué año comenzó la Primera Guerra Mundial?", "1914"],
    ["¿Qué dinastía gobernó Rusia hasta 1917?", "Los Románov"],
    ["¿Qué rey francés fue guillotinado en 1793?", "Luis XVI"],
    ["¿Cómo se llamaron las guerras entre Roma y Cartago?", "Las Guerras Púnicas"],
    ["¿Qué país actual era conocido como Persia?", "Irán"],
    ["¿Qué guerra enfrentó a Atenas y Esparta?", "La Guerra del Peloponeso"],
    ["¿Qué gran batalla naval de 1805 ganó Gran Bretaña?", "Trafalgar"],
    ["¿Qué líder mongol fundó el mayor imperio terrestre de la historia?", "Gengis Kan"],
    ["¿En qué año se firmó la Declaración de Independencia de EE. UU.?", "1776"]
  ],
  "🔬 Ciencia": [
    ["¿Qué elemento químico tiene el número atómico 79?", "El oro"],
    ["¿Qué partícula, descubierta en 2012, da masa a la materia?", "El bosón de Higgs"],
    ["¿Cuál es la velocidad aproximada de la luz en km/s?", "300.000 km/s"],
    ["¿Qué luna de Saturno tiene lagos de metano?", "Titán"],
    ["¿Quién descubrió la penicilina?", "Alexander Fleming"],
    ["¿Cuántos cromosomas tiene el ser humano?", "46"],
    ["¿Qué rama de la biología estudia los hongos?", "La micología"],
    ["¿Qué elemento tiene el símbolo W?", "El wolframio (tungsteno)"],
    ["¿Qué planeta tiene el día más largo del sistema solar?", "Venus"],
    ["¿Qué inventor creó la dinamita y da nombre a unos premios famosos?", "Alfred Nobel"],
    ["¿Cuál es el hueso más pequeño del cuerpo humano?", "El estribo"],
    ["¿Qué gas noble se usa en los carteles luminosos?", "El neón"]
  ],
  "🌍 Geografía": [
    ["¿Cuál es la capital de Mongolia?", "Ulán Bator"],
    ["¿Cuál es el lago más profundo del mundo?", "El lago Baikal"],
    ["¿Qué país tiene más islas del mundo?", "Suecia"],
    ["¿Cuál es la capital de Kazajistán?", "Astaná"],
    ["¿Qué estrecho separa Asia de América?", "El estrecho de Bering"],
    ["¿Qué gran país africano fue colonia de Bélgica?", "La República Democrática del Congo"],
    ["¿Cuál es el país menos poblado del mundo?", "Ciudad del Vaticano"],
    ["¿Cuál es la capital de Bután?", "Timbu"],
    ["¿En qué golfo está la ciudad de Dubái?", "El golfo Pérsico"],
    ["¿Cuál es el río más largo de Europa?", "El Volga"],
    ["¿Qué país tiene como capital Wellington?", "Nueva Zelanda"],
    ["¿Cuál es el desierto más árido del mundo?", "El desierto de Atacama"]
  ],
  "🎨 Arte y Literatura": [
    ["¿Quién escribió Cien años de soledad?", "Gabriel García Márquez"],
    ["¿Qué escritor ruso escribió Los hermanos Karamázov?", "Dostoievski"],
    ["¿En qué museo está La noche estrellada de Van Gogh?", "En el MoMA de Nueva York"],
    ["¿Quién pintó El jardín de las delicias?", "El Bosco"],
    ["¿Qué poeta escribió Veinte poemas de amor y una canción desesperada?", "Pablo Neruda"],
    ["¿Quién escribió En busca del tiempo perdido?", "Marcel Proust"],
    ["¿Quién escribió La metamorfosis?", "Franz Kafka"],
    ["¿Qué arquitecto diseñó el museo Guggenheim de Bilbao?", "Frank Gehry"],
    ["¿Quién pintó El nacimiento de Venus?", "Botticelli"],
    ["¿Qué escritora escribió Frankenstein?", "Mary Shelley"],
    ["¿Quién es el autor de Ulises?", "James Joyce"],
    ["¿Qué pintor neerlandés pintó La ronda de noche?", "Rembrandt"]
  ],
  "⚽ Deportes": [
    ["¿Qué selección ganó el primer Mundial de fútbol, en 1930?", "Uruguay"],
    ["¿Cuántos hoyos tiene un campo de golf estándar?", "18"],
    ["¿En qué ciudad se celebraron los primeros Juegos Olímpicos modernos?", "Atenas"],
    ["¿Cuál es la distancia oficial de una maratón?", "42,195 km"],
    ["¿En qué año ganó España su primer Mundial de baloncesto?", "2006"],
    ["¿Qué boxeador era conocido como «el más grande»?", "Muhammad Ali"],
    ["¿En qué país se inventó el voleibol?", "Estados Unidos"],
    ["¿Cuántos Roland Garros ha ganado Rafa Nadal?", "14"],
    ["¿Cuántos jugadores tiene un equipo de rugby XV en el campo?", "15"],
    ["¿Qué selección ganó la primera Eurocopa, en 1960?", "La URSS"],
    ["¿Qué nadador ganó 8 oros olímpicos en Pekín 2008?", "Michael Phelps"],
    ["¿Qué país ha ganado más Mundiales de fútbol?", "Brasil"]
  ],
  "🎬 Cine y Música": [
    ["¿Qué película ganó el primer Óscar a mejor película, en 1929?", "Alas (Wings)"],
    ["¿Quién compuso Las cuatro estaciones?", "Vivaldi"],
    ["¿Qué director rodó Ciudadano Kane?", "Orson Welles"],
    ["¿Qué banda publicó el álbum The Dark Side of the Moon?", "Pink Floyd"],
    ["¿Qué compositor siguió componiendo tras quedarse sordo?", "Beethoven"],
    ["¿Qué guitarrista prendió fuego a su guitarra en Monterrey, 1967?", "Jimi Hendrix"],
    ["¿Qué actriz protagonizó Desayuno con diamantes?", "Audrey Hepburn"],
    ["¿Quién dirigió 2001: Una odisea del espacio?", "Stanley Kubrick"],
    ["¿Qué película coreana ganó el Óscar a mejor película en 2020?", "Parásitos"],
    ["¿Quién compuso la banda sonora de Star Wars?", "John Williams"],
    ["¿Cuál es la película más taquillera de la historia?", "Avatar"],
    ["¿Qué director ha ganado más Óscar a mejor dirección, con cuatro?", "John Ford"]
  ]
};
